### ISSUE TITLE
Develop content template

### ISSUE THREAD

**Issue by kristiholmes** [data2health/reusable-data-best-practices#1]

**Comment by kristiholmes** [comment]
template - fork and write the chapter

**Draft chapter structure**

- Why is this important? - statement to provide context
- Topic Takeaways - a bulleted list of things you can read and implement (similar to top 10 PLoS Top 10 articles)
- Introduction
- Deep Dive into Takeaways
- Usecase(s)
- Summary

**Comment by kristiholmes** [comment]
seeking input on this draft structure from @newgene @mellybelly @KenGersing 
from @rchampieux @kristiholmes 

Please weigh in by the end of day, May 10 with comments or other input so that we can craft the pilot chapter.

**Comment by kristiholmes** [comment]
also, please think about nomenclature of the different sections.  should be pithy.

**Comment by kristiholmes** [comment]
Hi all - please take a look at these sections and see if this fits the desired framework for the best practices guidebook.  Once we get the OK, we will recruit a sample chapter to serve as a reference. Please comment below...

- [ ] Why is this important? (statement to provide context)
- [ ] Topic Takeaways (a bulleted list of things you can read and implement, similar to PLoS Top 10 articles)
- [ ] Introduction (problem statement, background, relevant contextual information)
- [ ] Deep Dive into Takeaways (space for discussion, lessons learned, caveats, etc. as necessary for the Topic Takeaways)
- [ ] Usecase(s) (it is always great to get an idea of who this information would be useful in the wild)
- [ ] Summary (wrap it up) 
- [ ] Acknowledgements (give credit for relevant funding, helpful colleagues, inspirations, etc.)

CC: @newgene @mellybelly @KenGersing @rchampieux @kristiholmes @data2health/pi

**Comment by mellybelly** [comment]
I think we should provide guidance on the use cases. There should be implementation examples. The summary may not be necessary if we have the topic takeaways (also these can link down into deeper content in the deep dive section).

**Comment by RoseRelevo** [comment]
RefWorks account UserName: MGuide password: MGuide

this is where we can start the database of citations and references

**Comment by mellybelly** [comment]
@RoseRelevo, @cgcook, or @newgene can you implement the above structure minus the summary + methods/evidence for all promised chapters? @RoseRelevo please make final comments about this latter point. All pls see #10 for info on the evidence.

**Comment by RoseRelevo** [comment]
Examples should not simply demonstrate that such a thing can be done, it should at least offer some insight as to why doing it one way (vs. another) is better.

Once any chapter or topic gets to be flushed out, I will be able to identify any current guidance or examples in the literature.

https://www.ncbi.nlm.nih.gov/books/NBK47095

This is AHRQ's methodological guidance, we've only been working on it for about 10 years :)
